# Plugin Configuration
application:
  # Enable Plugin Development Mode (true/false)
  dev: true

  # Plugin Namespace (where Factory will handle your classes)
  # It's strongly recommanded to change it !
  # Don't forget to change it in the composer.json too !
  namespace: App         

  # Default Plugin Capability
  capability: manage_options 

  # Plugin Assets Directory
  asset_dir: assets/         

  # Plugin Templates Directory
  template_dir: templates/   