<?php

namespace App;

use Graft\Framework\Annotation\AdminMenu;
use Graft\Framework\Injectable\Renderer;

/**
 * Plugin Administration Manager
 * Generated by Graft Plugin Skeleton
 * 
 * This is an example class
 */
class AdminManager
{
    /**
     * Renderer
     *
     * @var Renderer
     */
    private $renderer;


    /**
     * AdminManager Constructor
     *
     * @param Renderer $renderer Graft Renderer injected by autowiring
     */
    public function __construct(Renderer $renderer)
    {
        $this->renderer = $renderer;
    }


    /**
     * Main Plugin Administration Menu
     * Create Administration Menu with the Annotation below
     * 
     * @AdminMenu(title="Main", position=3)
     *
     * @return string
     */
    public function mainAdminMenu()
    {
        $template = "admin/mainmenu.html.twig";
        $templateOverwriteDir = $this->renderer->getTemplateOverrideHandler()->getTemplateOverrideDirectory();
        $templateOverwriteDir .= $template;

        // render the menu's template using Twig
        // set the third parameter to false if you don't want that this template can be overwrite. (default true)
        return $this->renderer->display(
            $template, 
            ["overwrite" => $templateOverwriteDir],
            true
        );
    }
}